name = input("Enter name: ")
city = input("Enter city: ")
hobby = input("Enter hobby: ")
language = input("Enter language: ")
print(f"==== Profile ====\nName: {name}\nCity: {city}\nHobby: {hobby}\nLanguage: {language}\n=================")