name = input("Enter your name: ")
age = int(input("Enter your age: "))
course = input("Enter course you are pursuing: ")
print(f"Hello, my name is {name}.")
print(f"I am {age} years old and pursuing {course}")
